# View pre-commit hooks at https://github.com/pre-commit/pre-commit-hooks#hooks-available
# !!!RUN pre-commit autoupdate!!! To get the latest versions. This gist has been collecting dust bunnies and cob webs.
# The commented repos/hooks will NOT autoupdate! If you're going to use them, uncomment and run pre-commit autoupdate.


default_stages: [commit, push]

fail_fast: true

minimum_pre_commit_version: '1.15.0'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: destroyed-symlinks
    -   id: fix-byte-order-marker
    -   id: file-contents-sorter
    -   id: forbid-new-submodules
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args: [--autofix, --indent]
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]  # Preserve Markdown hard linebreaks
          #
    # Docformatter https://pypi.org/project/docformatter/
-   repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args:
          - --in-place
          - -r
          - --blank
          - --recursive
          - --wrap-summaries=72
          - --wrap-descriptions=72
          - --pre-summary-newline
          - --make-summary-multi-line

    # Add trailing commas https://github.com/asottile/add-trailing-comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

    # iSort https://pycqa.github.io/isort/
-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args:
          - --trailing-comma
          - --use-parentheses
          - --balanced
          - --py=38
          - --profile=black
          - -l=79

    # Black https://black.readthedocs.io/en/stable/
-   repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
    -   id: black
        args:
          - --target-version=py38
          - --line-length=79


    # Unimport https://unimport.hakancelik.dev/#/
-   repo: https://github.com/hakancelik96/unimport
    rev: 1.2.1
    hooks:
    -   id: unimport
        args:
          - --remove
          - --include-star-import
          - --gitignore


    # Saftey https://pyup.io/safety/
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
    -   id: python-safety-dependencies-check
        files: pyproject.toml requirements.txt

    # Bandit https://github.com/PyCQA/bandit
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    -   id: bandit
        args: [--verbose, --skip, 'B101']
# Below is opinionated linters and formatters. Uncomment at your own risk!
    # Interrogate https://interrogate.readthedocs.io/en/latest/
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    -   id: interrogate
        args:
          - --fail-under=95
          - --verbose
          - --ignore-init-method
          - --ignore-init-module
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
#   # Dotenv Linter https://dotenv-linter.readthedocs.io/en/latest/index.html
# - repo: https://github.com/wemake-services/dotenv-linter
#   rev: 0.2.0  # Use the ref you want to point at
#   hooks:
# -   id: dotenv-linter
#
#     # MyPy https://github.com/pre-commit/mirrors-mypy
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: f687d36b12cd72d417bba07599ff27e734161768
#     hooks:
#     -   id: mypy
#         args: [--no-strict-optional, --ignore-missing-imports]
#
#     # Re-Order Imports https://github.com/asottile/reorder_python_imports
# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: 925baf70b8fe1467ac1712ddd6793d52978a4a72
#     hooks:
#     -   id: reorder-python-imports
#
#
#     # Swagger-CLI validator https://apitools.dev/swagger-cli/
# -   repo: https://github.com/APIDevTools/swagger-cli
#     rev: 9fec0bce6954a1bf7d396a6356f9c93780a92da7
#     hooks:
#     -   id: swagger-validation
#         args: ["validate", "<path to root swagger>"]
#
#   # Git Tickect https://giticket.readthedocs.io/en/latest/
# -  repo:  https://github.com/milin/giticket  # View docs to see how to set up custom ticket.
#    rev: <grab the latest commit hash>
#    hooks:
#    -   id:  giticket
#        args: ['--regex=PROJ-[0-9]', '--format={ticket} {commit_msg}']  # Optional

